---
  ## Backup de la base de datos zabbix
  ## Via sql
- name: BACKUP DE LA BASE DE DATOS DE ZABBIX
  hosts: all
  vars:
          repo_tag: zabbix_bdd
          timestamp: "{{lookup('pipe', 'date +%Y%m%d%H%M%SZ')}}"
          release_name: '{{ repo_tag }}_{{timestamp}}'
          archivo_backup: '{{release_name}}'
          vars:
          nombre_bdd: zabbix
          ruta_archivo_rx_my_cnf: /etc/myZBK.cnf
          ruta_archivo_my_cnf: /home/myZBK.cnf
          ruta_archivo_src_cnf: /home/ZabbixBDDBackup/.my.cnf
          ruta_carpeta_backups: /etc/ZabbixRespBDD
          ruta_carpeta_repogit: /home/ZabbixBDDBackup
          ruta_archivo_repogit: /home/ZabbixBDDBackupGit.zip
 
  tasks:

          - name: Validar si existe el archivo rx con las creedenciales para ingresar a la base MySQL
            stat:
                    path: '{{ ruta_archivo_rx_my_cnf }}'
            register: existe_arch_rx_mycnf

          - name: Eliminar el archivo rx con las credenciales para ingresar a la base MySQL
            file:
                    path: '{{ ruta_archivo_rx_my_cnf }}'
                    state: absent
            when: existe_arch_rx_mycnf.stat.exists

          - name: Validar si ya se encuentra instalado el git validando el servicio
            service_facts:
          - debug:
                  msg: Docker installed!
            when: "'git' in services"

          - name: Instalar la aplicación git para poder recuperar los recursos correspondientes
            dnf:
                    name: git
                    state: present
            when: not "'git' in services"

          - name: Validar si existe la carpeta con la información del proyecto contenido en el git
            stat:
                    path: '{{ ruta_carpeta_repogit }}'
            register: existe_ruta_carpeta_repogit

          - name: Eliminar la carpeta con el contenido del proyecto en el git
            file:
                    path: '{{ ruta_carpeta_repogit }}'
                    state: absent
            when: existe_ruta_carpeta_repogit.stat.exists


          - name: Descargar el archivo con las credenciales de conexión a la base de datos usando GIT7
            git:
                    repo: https://github.com/jzavala74mz/ATower.ZabbixBDDBackup
                    dest: '{{ ruta_carpeta_repogit }}'
                    archive: '{{ ruta_archivo_repogit }}'

          - name: Validar si el archivo de credenciales que se va a utilizar existe
            stat:
                    path: '{{ ruta_archivo_my_cnf }}'
            register: existe_archivo_my_cnf

          - name: Si existe el archivo my.cnf a utilizar lo borramos para usar la versión mas actualizada
            file:
                    path: '{{ ruta_archivo_my_cnf }}'
                    state: absent
            when: existe_archivo_my_cnf.stat.exists



          - name: Copiar el archivo con las credenciales de acceso a la base de datos con destino '{{ ruta_archivo_my_cnf }}'
            copy:
                    src: '{{ ruta_archivo_src_cnf }}'
                    dest: '{{ ruta_archivo_my_cnf }}'
                    owner: root
                    backup: no
                    remote_src: yes
          
          - name: Validar si ya existe la carpeta de los resguardos de la base de datos
            stat:
                    path: '{{ ruta_carpeta_backups }}'
            register: existe_ruta_backups

          - name: Create a directory if it does not exist
            file:
                    path: '{{ ruta_carpeta_backups }}'
                    state: directory
                    mode: '0755'
            when: not existe_arch_rx_mycnf.stat.exists

          - name: Respaldar la base de datos de zabbix al archivo de retorno especificado
            mysql_db:
                    name: zabbix
                    login_user: root
                    encoding: utf8
                    state: dump
                    config_file: '{{ ruta_archivo_my_cnf }}'
                    target: '{{ ruta_carpeta_backups }}/{{ archivo_backup }}'

          ## LIMPIAR O OEÑLIMINAR LOS ARCHIVO Y CARPETAS QUE SE GENERARON CONTENIDOS EN LAS SIGUIENTES
          ## VARIABLE
          ## ruta_archivo_rx_my_cnf: /etc/myZBK.cnf
          ## ruta_archivo_my_cnf: /home/myZBK.cnf
          ## ruta_archivo_src_cnf: /home/ZabbixBDDBackup/.my.cnf
          ## ruta_carpeta_backups: /etc/ZabbixRespBDD
          ## ruta_carpeta_repogit: /home/ZabbixBDDBackup
          ## ruta_archivo_repogit: /home/ZabbixBDDBackupGit.zip
          - name: Depurando información
            file:
                    path: "{{ item }}"
                    state: absent
            with_items:
                    - '{{ ruta_archivo_rx_my_cnf }}'
                    - '{{ ruta_archivo_my_cnf }}'
                    - '{{ ruta_archivo_src_cnf }}'
                    - '{{ ruta_carpeta_repogit }}'
                    - '{{ ruta_archivo_repogit }}'

