---
  ## Backup de la base de datos zabbix
  ## Via sql
- name: BACKUP DE LA BASE DE DATOS DE ZABBIX
  hosts: all
  vars:
          repo_tag: zabbix_bdd
          timestamp: "{{lookup('pipe', 'date +%Y%m%d%H%M%SZ')}}"
          release_name: '{{ repo_tag }}_{{timestamp}}'
          archivo_backup: '{{release_name}}'
          vars:
          nombre_bdd: zabbix
          ruta_archivo_rx_my_cnf: /etc/myZBK.cnf
 
  tasks:

          - name: Validar si existe el archivo rx con las creedenciales para ingresar a la base MySQL
            stat:
                    path: '{{ ruta_archivo_rx_my_cnf }}'
            register: existe_arch_rx_mycnf

          - name: Eliminar el archivo rx con las credenciales para ingresar a la base MySQL
            file:
                    path: '{{ ruta_archivo_rx_my_cnf }}'
                    state: absent
            when: existe_arch_rx_mycnf.stat.exists

          - name: Validar si ya se encuentra instalado el git validando el servicio
            service_facts:
          - debug:
                  msg: Docker installed!
            when: "'git' in services"

          - name: Instalar la aplicación git para poder recuperar los recursos correspondientes
            dnf:
                    name: git
                    state: present
            when: not "'git' in services"

          - name: Descargar el archivo con las credenciales de conexión a la base de datos
            git:
                    repo: https://github.com/jzavala74mz/ATower.ZabbixBDDBackup
                    dest: /home/ZabbixBDDBackup
                    archive: /home/file.zip

          - name: Copiar el archivo con las credenciales de acceso a la base de datos con destino .my2.cnf
            copy:
                    src: /home/ZabbixBDDBackup/.my.cnf
                    dest: /home/.my2.cnf
                    owner: root
                    backup: no
                    remote_src: no
          
          - name: Create a directory if it does not exist
            file:
                    path: /etc/ZabbixRespBDD
                    state: directory
                    mode: '0755'

          - name: Respaldar la base de datos de zabbix al archivo de retorno especificado
            mysql_db:
                    name: zabbix
                    login_user: root
                    encoding: utf8
                    state: dump
                    config_file: /home/.my2.cnf
                    target: '/etc/ZabbixRespBDD/{{ archivo_backup }}'


